version: '3.8'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mycats
      POSTGRES_DB: mycats
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./db-startup.sh:/docker-entrypoint-initdb.d/db-startup.sh
      - postgres_data:/var/lib/postgresql/data

  api:
    image: my-cats/api
    restart: unless-stopped
    build:
      context: ./api
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_STRING: postgres://mycats:${POSTGRES_PASSWORD}@postgres:5432/mycats
      PORT: 80
    expose:
      - 80
    networks:
      - default

  webapp:
    image: my-cats/webapp
    restart: unless-stopped
    build:
      context: ./webapp
      args:
        - API_BASE_URL=/api
        - GMAPS_API_KEY=${GMAPS_API_KEY}
    expose:
      - 80
    networks:
      - default

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - api
      - webapp
    networks:
      - default
    ports:
      - ${PROXY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    command: [ nginx, "-g", "daemon off;" ]

volumes:
  postgres_data:
