version: '3.8'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: my_cats
      POSTGRES_DB: my_cats
      POSTGRES_PASSWORD: h3ll0w0rld
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: my-cats/api
    restart: unless-stopped
    build:
      context: ./api
    depends_on:
      - postgres
    environment:
      DB_CONNECTON_STRING: postgres://mycats:h3ll0w0rld@postgres:5432/mycats
      PORT: 80
    expose:
      - 80
    networks:
      - default

  webapp:
    image: my-cats/webapp
    restart: unless-stopped
    build:
      context: ./webapp
    expose:
      - 80
    networks:
      - default

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - api
      - webapp
    networks:
      - default
    ports:
      - 9090:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    command: [ nginx, "-g", "daemon off;" ]
volumes:
  postgres_data:
