name: Run Tests

on:
  push:
    branches: [ main, dev ]

jobs:
  test-api:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run API Test
        run: cd api/ && yarn && yarn test